import numpy as np
import openmdao.api as om
from attrs import field, define

from h2integrate.core.utilities import BaseConfig, merge_shared_inputs


@define
class AmmoniaSynLoopPerformanceConfig(BaseConfig):
    """
    Configuration inputs for the ammonia synthesis loop performance model.
    *Starred inputs are from tech_config/ammonia/model_inputs/shared_parameters
    The other inputs are from tech_config/ammonia/model_inputs/performance_parameters

    Attributes:
        *production_capacity (float): The total production capacity of the ammonia synthesis loop
            (in kg ammonia per hour)
        energy_demand (float): The total energy demand of the ammonia synthesis loop
            (in MWh electricity per kg ammonia).
        nitrogen_conversion_rate (float): The mass fraction of nitrogen converted to ammonia in
            the synthesis loop (as a decimal).
        hydrogen_conversion_rate (float): The mass fraction of hydrogen converted to ammonia in
            the synthesis loop (as a decimal).
        ammonia_conversion_eff (float): The total mass percentage of nitrogen and hydrogen
            converted to ammonia in the synthesis loop (as a deciamal).
        *catalyst_consumption_rate (float): The mass ratio of catalyst consumed by the reactor over
            its lifetime to ammonia produced
        *catalyst_replacement_interval (float): The interval in years when the catalyst is replaced
        heat_output (float): The total heat output of the ammonia synthesis loop
            (in MWh thermal per kg ammonia)
    """

    production_capacity: float = field()
    energy_demand: float = field()
    nitrogen_conversion_rate: float = field()
    hydrogen_conversion_rate: float = field()
    ammonia_conversion_eff: float = field()
    catalyst_consumption_rate: float = field()
    catalyst_replacement_interval: float = field()
    heat_output: float = field()


class AmmoniaSynLoopPerformanceModel(om.ExplicitComponent):
    """
    OpenMDAO component modeling the performance of an ammonia synthesis loop.

    This component calculates the hourly ammonia production based on the available
    hydrogen, nitrogen, and electricity inputs, considering the stoichiometric and
    energetic requirements of the synthesis process. It also computes the unused
    hydrogen, nitrogen, and electricity (as heat), as well as the total ammonia
    produced over the modeled period.
    Attributes
    ----------
    config : AmmoniaSynLoopPerformanceConfig
        Configuration object containing model parameters such as energy demand,
        nitrogen conversion rate, and hydrogen conversion rate.
    Inputs
    ------
    hydrogen_in : array [kg/h]
        Hourly hydrogen feed to the synthesis loop.
    nitrogen_in : array [kg/h]
        Hourly nitrogen feed to the synthesis loop.
    electricity_in : array [MW]
        Hourly electricity supplied to the synthesis loop.
    Outputs
    -------
    ammonia_out : array [kg/h]
        Hourly ammonia produced by the synthesis loop.
    nitrogen_out : array [kg/h]
        Hourly unused nitrogen after synthesis loop.
    hydrogen_out : array [kg/h]
        Hourly unused hydrogen after synthesis loop.
    electricity_out : array [MW]
        Hourly unused electricity after synthesis loop.
    heat_out : array [MW]
        Hourly heat generated by synthesis loop.
    catalyst_mass: float [kg]
        Total catalyst mass needed in synthesis loop.
    total_ammonia_produced : float [kg/year]
        Total ammonia produced over the modeled period.
    Notes
    -----
    The ammonia production is limited by the most constraining input (hydrogen,
    nitrogen, or electricity) at each timestep. The component assumes perfect
    conversion efficiency up to the limiting reagent or energy input.
    """

    def initialize(self):
        self.options.declare("plant_config", types=dict)
        self.options.declare("tech_config", types=dict)

    def setup(self):
        self.config = AmmoniaSynLoopPerformanceConfig.from_dict(
            merge_shared_inputs(self.options["tech_config"]["model_inputs"], "performance")
        )

        self.add_input(
            "hydrogen_in", val=0.0, shape_by_conn=True, copy_shape="ammonia_out", units="kg/h"
        )
        self.add_input(
            "nitrogen_in", val=0.0, shape_by_conn=True, copy_shape="ammonia_out", units="kg/h"
        )
        self.add_input(
            "electricity_in", val=0.0, shape_by_conn=True, copy_shape="ammonia_out", units="MW"
        )

        self.add_output(
            "ammonia_out", val=0.0, shape_by_conn=True, copy_shape="hydrogen_in", units="kg/h"
        )
        self.add_output(
            "nitrogen_out", val=0.0, shape_by_conn=True, copy_shape="nitrogen_in", units="kg/h"
        )
        self.add_output(
            "hydrogen_out", val=0.0, shape_by_conn=True, copy_shape="hydrogen_in", units="kg/h"
        )
        self.add_output(
            "electricity_out", val=0.0, shape_by_conn=True, copy_shape="nitrogen_in", units="MW"
        )
        self.add_output(
            "heat_out", val=0.0, shape_by_conn=True, copy_shape="nitrogen_in", units="MW"
        )
        self.add_output("catalyst_mass", val=0.0, units="kg")
        self.add_output("total_ammonia_produced", val=0.0, units="kg/year")

    def compute(self, inputs, outputs):
        # Get config values
        nh3_cap = self.config.production_capacity  # kg NH3 per hour
        energy_demand = self.config.energy_demand  # MWh per kg NH3
        n2_rate = self.config.nitrogen_conversion_rate  # kg N2 per kg NH3
        h2_rate = self.config.hydrogen_conversion_rate  # kg H2 per kg NH3
        nh3_eff = self.config.ammonia_conversion_eff  # kg NH3 per (kg H2 + kg N2)
        cat_consume = self.config.catalyst_consumption_rate  # kg Cat per kg NH3
        cat_replace = self.config.catalyst_replacement_interval  # years
        heat_output = self.config.heat_output  # MWh per kg NH3

        # Inputs (arrays of length 8760)
        h2_in = inputs["hydrogen_in"]
        n2_in = inputs["nitrogen_in"]
        elec_in = inputs["electricity_in"]

        # Calculate max NH3 production for each input - all kg NH3 / hr
        nh3_from_h2 = h2_in * nh3_eff / h2_rate
        nh3_from_n2 = n2_in * nh3_eff / n2_rate
        nh3_from_elec = elec_in / energy_demand

        # Limiting NH3 production per hour
        nh3_prod = np.minimum.reduce([nh3_from_h2, nh3_from_n2, nh3_from_elec])
        nh3_prod = np.minimum.reduce([nh3_prod, nh3_cap])

        # Calculate unused inputs
        used_h2 = nh3_prod * h2_rate
        used_n2 = nh3_prod * n2_rate
        used_elec = nh3_prod * energy_demand

        # Calculate catalyst mass
        cat_rate = cat_consume * nh3_prod  # kg Cat / hr
        cat_mass = np.sum(cat_rate) * cat_replace  # kg

        outputs["ammonia_out"] = nh3_prod
        outputs["hydrogen_out"] = h2_in - used_h2
        outputs["nitrogen_out"] = n2_in - used_n2
        outputs["electricity_out"] = elec_in - used_elec
        outputs["heat_out"] = nh3_prod * heat_output
        outputs["catalyst_mass"] = cat_mass
        outputs["total_ammonia_produced"] = nh3_prod.sum()


@define
class AmmoniaSynLoopCostConfig(BaseConfig):
    """
    Configuration inputs for the ammonia synthesis loop cost model.
    *Starred inputs are from tech_config/ammonia/model_inputs/shared_parameters
    The other inputs are from tech_config/ammonia/model_inputs/cost_parameters

    Attributes:
        ---Scaling---
        *production_capacity (float): The total production capacity of the ammonia synthesis loop
            (in kg ammonia per hour)
        baseline_capacity (float): The capacity of the baseline ammonia plant for cost simulations
            (in kg ammonia per hour)
        base_cost_year (int): Year in which base USD costs are derived - to be adjusted using
            CEPCI for capex and CPI for opex.
        capex_scaling_exponent (float): Power applied to ratio of capacities when calculating CAPEX
            from a baseline value at a different capacity.
        labor_scaling_exponent (float): Power applied to ratio of capacities when calculating labor
            cost from a baseline value at a different capacity.
        ---CAPEX---
        synloop_capex_base (float): Baseline capital expenditure for the synthesis loop [$].
        heat_capex_base (float) : Baseline capital expenditure for the boiler and steam turbine [$].
        cool_capex_base (float) : Baseline capital expenditure for the cooling tower [$].
        other_direct_capex_base (float): Other baseline direct capital expenditures [$].
        land_capex_base (float): Baseline capital expenditure for land to construct the plant [$].
        deprec_noneq_capex_base (float): Baseline depreciable nonequipment capital expenditures [$].
        ---OPEX---
        labor_rate_base (float) : Baseline all-in labor rate [$/hr].
        num_workers_base (float) : Baseline number of workers for the entire ammonia plant [-].
        hours_yr (float) : Work hours per year per worker [hr/year].
        gen_admin (float) : General and administrative expenses as a percentage of labor [pct].
        prop_tax_ins (float) : Property tax and insurance as a percentage of labor [pct].
        oxygen_byproduct_rate
        water_consumption_rate (float): The mass ratio of cooling water consumed by the reactor over
            its lifetime to ammonia produced
        *catalyst_consumption_rate (float): The mass ratio of catalyst consumed by the reactor over
            its lifetime to ammonia produced
        rebuild_cost (float): Cost to teardown/rebuild reactor after catalyst replacement [USD].
        ---Feedstock Costs---
        hydrogen_price
        electricity_price
        cooling_water_price
        catalyst_price
        oxygen_price

    """

    capex: float = field()
    rebuild_cost: float = field()


class AmmoniaSynLoopCostModel(om.ExplicitComponent):
    """
    OpenMDAO component modeling the cost of an ammonia synthesis loop.

    This component outputs the capital expenditure (CapEx) and annual operating
    expenditure (OpEx) associated with the synthesis loop, based on provided
    configuration values.

    Attributes
    ----------
    config : AmmoniaSynLoopCostConfig
        Configuration object containing CapEx and annual rebuild cost.

    Outputs
    -------
    CapEx : float [$]
        Capital expenditure for the synthesis loop.
    OpEx : float [$ per year]
        Annual operating expenditure (catalyst replacement/rebuild).
    Notes
    -----
    This model assumes all OpEx is due to annualized catalyst replacement/rebuild.
    """

    def initialize(self):
        self.options.declare("plant_config", types=dict)
        self.options.declare("tech_config", types=dict)

    def setup(self):
        self.config = AmmoniaSynLoopCostConfig.from_dict(
            merge_shared_inputs(self.options["tech_config"]["model_inputs"], "cost")
        )

        self.add_output("CapEx", val=0.0, units="USD")
        self.add_output("OpEx", val=0.0, units="USD/year")

    def compute(self, inputs, outputs):
        # Get config values
        outputs["CapEx"] = self.config.capex
        outputs["OpEx"] = self.config.rebuild_cost
