name: "technology_config"
description: "This hybrid plant produces methanol"

technologies:
  methanol:
    performance_model:
      model: "methanol_plant_performance"
    cost_model:
      model: "methanol_plant_cost"
    financial_model:
      model: "methanol_plant_financial"
    model_inputs:
      shared_parameters:
        conversion_tech: "smr"
        plant_capacity_kgpy: 127893196.8
      performance_parameters:
        capacity_factor: 0.9
        co2e_emit_ratio: 1.13442
        h2o_consume_ratio: 2.669877132
        h2_consume_ratio: 0.0
        co2_consume_ratio: 0.0
        elec_consume_ratio: 0.1
        meoh_syn_cat_consume_ratio: 0.00000036322492251
        meoh_atr_cat_consume_ratio: 0.0000013078433938
        lng_consume_ratio: 1.61561859
        elec_produce_ratio: 0.338415339
      cost_parameters:
        toc_kg_y: 0.782749307
        foc_kg_y2: 0.020675078
        voc_kg: 0.012271827
        meoh_syn_cat_price: 615.274273
        meoh_atr_cat_price: 747.9768786
        lng_price: 4.0
        elec_sales_price: 0.027498168
      finance_parameters:
        # Sources in NETL-PUB-22580: Exhibit 3-5 and Exhibit 3-7
        discount_rate: 0.0707
        tasc_toc_multiplier: 1.093
        fixed_charge_rate: 0.0707
