name: "technology_config"
description: "This hybrid plant produces steel"

technologies:
  methanol:
    performance_model:
      model: "methanol_plant_performance"
    cost_model:
      model: "methanol_plant_cost"
    financial_model:
      model: "methanol_plant"
    model_inputs:
      shared_parameters:
        conversion_tech: "smr"
        plant_capacity_kgpy: 127893196.8
      performance_parameters:
        capacity_factor: 0.9
      finance_parameters:
        discount_rate: 0.0707
        tasc_toc_multiplier: 1.093
