name: "technology_config"
description: "This hybrid plant produces steel"

technologies:
  methanol:
    performance_model:
      model: "methanol_plant_performance"
    cost_model:
      model: "methanol_plant_cost"
    financial_model:
      model: "methanol_plant_financial"
    model_inputs:
      shared_parameters:
        conversion_tech: "smr"
        conversion_model: "netl"
      performance_parameters:
        lng: 10000000
        lng_consumption: 0.4
      cost_parameters:
        lng: 10000000
        capex_factor: 100
        plant_capacity_kgpy: 25000000
        lng_cost: 2.0
      finance_parameters:
        discount_rate: 0.7
