name: "technology_config"
description: "This hybrid plant produces methanol"

technologies:
  hydrogen:
    performance_model:
      model: "combined_geoh2_plant_performance"
    cost_model:
      model: "combined_geoh2_plant_cost"
    financial_model:
      model: "combined_geoh2_financial"
    model_inputs:
      shared_parameters:
        well_lifetime: 20
      performance_parameters:
        grain_size: 0.001
        serp_rate: 2.0e-10
        caprock_depth: 100
        borehole_depth: 1000
        inj_prod_distance: 100
        reaction_zone_width: 10
        site_prospectivity: 0.7
        initial_wellhead_flow: 200
        gas_reservoir_size: 1000
        iron_II_content: 15
        bulk_density: 2700
        water_temp: 90
      cost_parameters:
        test_drill_cost: 500000
        permit_fees: 905
        acreage: 500
        rights_cost: 3
        completion_cost: 4000000
        success_chance: 20
        fixed_opex: 200000
        variable_opex: 0.30
