name: "technology_config"
description: "This hybrid plant produces methanol"

technologies:
  methanol:
    performance_model:
      model: "co2h_methanol_plant_performance"
    cost_model:
      model: "co2h_methanol_plant_cost"
    financial_model:
      model: "co2h_methanol_plant_financial"
    model_inputs:
      shared_parameters:
        plant_capacity_kgpy: 127893196.8
      performance_parameters:
        capacity_factor: 0.9
        co2e_emit_ratio: 0.020296
        h2o_consume_ratio: 0.988
        h2_consume_ratio: 0.195
        co2_consume_ratio: 1.423
        elec_consume_ratio: 0.09466667
        meoh_syn_cat_consume_ratio: 0.00000128398
        ng_consume_ratio: 0.073511601
      cost_parameters:
        ng_lhv: 47.1
        toc_kg_y: 1.0633873
        foc_kg_y2: 0.020743864
        voc_kg: 0.00079
        meoh_syn_cat_price: 615.274273
        ng_price: 4.0
        co2_price: 0.0549007
      finance_parameters:
        # Sources in NETL-PUB-22580: Exhibit 3-5 and Exhibit 3-7
        tasc_toc_multiplier: 1.093
        fixed_charge_rate: 0.0707
